#ifdef INSTR_REC
INSTR_REC(	aaa  )
INSTR_REC(	aad  )
INSTR_REC(	aam  )
INSTR_REC(	aas  )
INSTR_REC(	adc  )
INSTR_REC(	add  )
INSTR_REC(	and_ )
INSTR_REC(	arpl )
INSTR_REC(	bound)
INSTR_REC(	bsf  )
INSTR_REC(	bsr  )
INSTR_REC(	bswap)
INSTR_REC(	bt   )
INSTR_REC(	btc  )
INSTR_REC(	btr  )
INSTR_REC(	bts  )
INSTR_REC(	call )
INSTR_REC(	callr)
INSTR_REC(	callf)
INSTR_REC(	callfp)
INSTR_REC(	cbw  )
INSTR_REC(	cdB  )
INSTR_REC(	clc  )
INSTR_REC(	cld  )
INSTR_REC(	cli  )
INSTR_REC(	clts )
INSTR_REC(	cmc  )
INSTR_REC(	cmp  )

INSTR_REC(	cmpxchg  )
INSTR_REC(	cmpxchg8b  )
INSTR_REC(	cwd  )
INSTR_REC(	cwde )
INSTR_REC(	daa  )
INSTR_REC(	das  )
INSTR_REC(	dec  )
INSTR_REC(	udiv )
INSTR_REC(	enter)
INSTR_REC(	hlt  )
INSTR_REC(	idiv )
INSTR_REC(	imul )
INSTR_REC(	imul1)
INSTR_REC(	imul2)
INSTR_REC(	imul3)
INSTR_REC(	in   )
INSTR_REC(	inc  )
INSTR_REC(	int3  )
INSTR_REC(	intx  )
INSTR_REC(	into  )
INSTR_REC(	invlpg)
INSTR_REC(	invd  )
INSTR_REC(	iret  )
INSTR_REC(	jcxz  )
INSTR_REC(	jmp   )
INSTR_REC(	jmpr  )
INSTR_REC(	jmpf  )
INSTR_REC(	jmpfp )
INSTR_REC(	lldt  )
INSTR_REC(	lmsw  )

INSTR_REC(	lsl  )
INSTR_REC(	lss  )
INSTR_REC(	ltr  )
INSTR_REC(	mov  )

INSTR_REC(	movsx  )
INSTR_REC(	movzx  )
INSTR_REC(	mul  )
INSTR_REC(	neg  )
INSTR_REC(	nop  )
INSTR_REC(	not_  )
INSTR_REC(	or_  )
INSTR_REC(	out  )

INSTR_REC(	pop  )
INSTR_REC(	popa  )
INSTR_REC(	popf  )
INSTR_REC(	push  )
INSTR_REC(	pusha )
INSTR_REC(	pushf )
INSTR_REC(	rcln  )
INSTR_REC(	rcrn  )
INSTR_REC(	rcl1  )
INSTR_REC(	rcr1  )

INSTR_REC(	sahf  )
INSTR_REC(	saln  )
INSTR_REC(	sarn  )
INSTR_REC(	sal1  )
INSTR_REC(	sar1  )
INSTR_REC(	sbb   )

INSTR_REC(	setx  )
INSTR_REC(	sgdt  )
INSTR_REC(	sidt  )
INSTR_REC(	shrn  )
INSTR_REC(	shr1  )
INSTR_REC(	shln  )
INSTR_REC(	shl1  )
INSTR_REC(	lahf  )
INSTR_REC(	lar   )
INSTR_REC(	lds   )
INSTR_REC(	lea   )
INSTR_REC(	leave )
INSTR_REC(	les   )
INSTR_REC(	lfs   )
INSTR_REC(	lgdt  )
INSTR_REC(	lidt  )
INSTR_REC(	lgs   )
INSTR_REC(	ret   )
INSTR_REC(	retf  )
INSTR_REC(	retfn )
INSTR_REC(	retn  )
INSTR_REC(	roln  )
INSTR_REC(	rorn  )
INSTR_REC(	rol1  )
INSTR_REC(	ror1  )
INSTR_REC(	shld  )
INSTR_REC(	shrd  )
INSTR_REC(	sldt  )
INSTR_REC(	smsw  )
INSTR_REC(	stc   )
INSTR_REC(	std_  )
INSTR_REC(	sti   )

INSTR_REC(	str   )
INSTR_REC(	sub   )
INSTR_REC(	subb  )
INSTR_REC(	test  )
INSTR_REC(	verr  )
INSTR_REC(	verw  )
INSTR_REC(	wait  )
INSTR_REC(	wbinvd  )
INSTR_REC(	xchg  )
INSTR_REC(	xlat  )
INSTR_REC(	xor_  )
INSTR_REC(	loop  )
INSTR_REC(	loopz)
INSTR_REC(	loopnz)
INSTR_REC(	cpuid )
INSTR_REC(	xadd  )
INSTR_REC(	rsm   )
INSTR_REC(	rdmsr )
INSTR_REC(	wrmsr )

INSTR_REC(	JO     )
INSTR_REC(	JNO	   )
INSTR_REC(	JB	   )
INSTR_REC(	JNB	   )
INSTR_REC(	JE	   )
INSTR_REC(	JNE	   )
INSTR_REC(	JNA	   )
INSTR_REC(	JA     )
INSTR_REC(	JS	   )
INSTR_REC(	JNS	   )
INSTR_REC(	JPE	   )
INSTR_REC(	JPO	   )
INSTR_REC(	JL	   )
INSTR_REC(	JNL	   )
INSTR_REC(	JNG    )
INSTR_REC(	JG	   )
INSTR_REC(	SETO   )
INSTR_REC(	SETNO  )
INSTR_REC(	SETB   )
INSTR_REC(	SETNB  )
INSTR_REC(	SETE   )
INSTR_REC(	SETNE  )
INSTR_REC(	SETNA  )
INSTR_REC(	SETA   )
INSTR_REC(	SETS   )
INSTR_REC(	SETNS  )
INSTR_REC(	SETPE  )
INSTR_REC(	SETPO  )
INSTR_REC(	SETL   )
INSTR_REC(	SETNL  )
INSTR_REC(	SETNG  )
INSTR_REC(	SETG   )
INSTR_REC(	CMOVO     )
INSTR_REC(	CMOVNO	   )
INSTR_REC(	CMOVB	   )
INSTR_REC(	CMOVNB	   )
INSTR_REC(	CMOVE	   )
INSTR_REC(	CMOVNE	   )
INSTR_REC(	CMOVNA	   )
INSTR_REC(	CMOVA     )
INSTR_REC(	CMOVS	   )
INSTR_REC(	CMOVNS	   )
INSTR_REC(	CMOVPE	   )
INSTR_REC(	CMOVPO	   )
INSTR_REC(	CMOVL	   )
INSTR_REC(	CMOVNL	   )
INSTR_REC(	CMOVNG    )
INSTR_REC(	CMOVG	   )
INSTR_REC(	CMPXCHG486 )
INSTR_REC(	RDPMC      )
INSTR_REC(SYSEXIT	   )
INSTR_REC(SYSENTER	   )
INSTR_REC(	RDTSC      )
INSTR_REC(	SYSRET     )
INSTR_REC(	SYSCALL    )
INSTR_REC( RDTSCP )
INSTR_REC( XGETBV )
INSTR_REC( XSETBV )
INSTR_REC( FWAIT)
INSTR_REC(	 rcl)
INSTR_REC(	 rcr)
INSTR_REC(	 rol)
INSTR_REC(	 ror)
INSTR_REC(	 sal)
INSTR_REC(	 sar)
INSTR_REC(	shr)

INSTR_REC(	stos  )
INSTR_REC(	outs  )
INSTR_REC(	cmps  )
INSTR_REC(	movs  )
INSTR_REC(	lods  )
INSTR_REC(	ins   )
INSTR_REC(	scas  )
INSTR_REC(	undefined )

INSTR_REC(	swapgs )
INSTR_REC(	monitor)
INSTR_REC(	mwait  )
INSTR_REC(	ud2    )
INSTR_REC(	crc32  )
INSTR_REC(	emms   )
INSTR_REC(	ldmxcsr)
INSTR_REC(	stmxcsr)
INSTR_REC(	lfence )
INSTR_REC(	mfence )
INSTR_REC(	sfence )
INSTR_REC(	prefetch)
INSTR_REC(	esc   )
INSTR_REC(	FXRSTOR )
INSTR_REC(	FXSAVE )
//#include "sse_id.h"

//#include "fpu_id.h"



//
#include "fpu-id-def.h"
#include "sse-id-def.h"

#endif