 #if defined (OPER_FMT_REC)

OPER_FMT_REC(acc_dx	      )
OPER_FMT_REC(dx_acc	      )
OPER_FMT_REC(accEv	      )
OPER_FMT_REC(accIb	      )
OPER_FMT_REC(accIv 	      )
OPER_FMT_REC(accReg	      )
OPER_FMT_REC(accXv        )
OPER_FMT_REC(regIv	      )
OPER_FMT_REC(Ap		      )
OPER_FMT_REC(DXXv         )
OPER_FMT_REC(Eb		      )
OPER_FMT_REC(Ep		      )
OPER_FMT_REC(Ev		      )
OPER_FMT_REC(Ev1	      )
OPER_FMT_REC(EvCL	      )
OPER_FMT_REC(EvGv	      )
OPER_FMT_REC(EvvGv	      )
OPER_FMT_REC(EvGvCL	      )
OPER_FMT_REC(EvGvIb       )
OPER_FMT_REC(EvGvIv	      )
OPER_FMT_REC(EvIb	      )
OPER_FMT_REC(EvIv	      )
OPER_FMT_REC(Ew		      )
OPER_FMT_REC(EwGw	      )
OPER_FMT_REC(FSGS	      )
OPER_FMT_REC(Fv		      )
OPER_FMT_REC(GvEw         )
OPER_FMT_REC(GvMa	      )
OPER_FMT_REC(GvMp	      )
OPER_FMT_REC(Ib		      )
OPER_FMT_REC(Ibacc	      )
OPER_FMT_REC(fmt_int3     )
OPER_FMT_REC(Iv		      )
OPER_FMT_REC(Iw		      )
OPER_FMT_REC(IwIb	      )
OPER_FMT_REC(Jb		      )
OPER_FMT_REC(Jv		      )
OPER_FMT_REC(Mp		      )
OPER_FMT_REC(Ms		      )
OPER_FMT_REC(Mv		      )
OPER_FMT_REC(GvMv	      )
OPER_FMT_REC(Ovacc	      )
OPER_FMT_REC(RdCd	      )
OPER_FMT_REC(RdDd	      )
OPER_FMT_REC(RdTd	      )
OPER_FMT_REC(fmt_REG	  )
OPER_FMT_REC(fmt_SREG	  )
OPER_FMT_REC(SwEw         )
OPER_FMT_REC(XvYv         )
OPER_FMT_REC(Yvacc        )
OPER_FMT_REC(YvDX         )
OPER_FMT_REC(	mem32   )
OPER_FMT_REC(	VW	    )
OPER_FMT_REC(	VWIb	)
OPER_FMT_REC(	VPG	    )
OPER_FMT_REC(	PBVM    )
OPER_FMT_REC(	GPW	    )
OPER_FMT_REC(	GdV  	)
OPER_FMT_REC(	GdPV	)
OPER_FMT_REC(	EdPV	)
OPER_FMT_REC(	VM   	)
OPER_FMT_REC(	MG	    )
OPER_FMT_REC(  fmt_xlat )
OPER_FMT_REC(	fmt_none)
OPER_FMT_REC(	fmt_esc )
OPER_FMT_REC(	mem512 )

#include "fpu-fmt-def.h"
#include "sse-fmt-def.h"
#endif