 #if defined (OPER_TYPE_REC)
OPER_TYPE_REC(	rm          )  // rm is op1
OPER_TYPE_REC(	rm1          )  // rm is op1
OPER_TYPE_REC(	rm2          )  // reg=dst, rm is op1, only in mul r,rm,imm
OPER_TYPE_REC(	rm8          )
OPER_TYPE_REC(	rm16         )
OPER_TYPE_REC(	rmf          )
OPER_TYPE_REC(	rm_r16       )
OPER_TYPE_REC(	rm_r32       )
OPER_TYPE_REC(	rm_cr        )
OPER_TYPE_REC(	rm_dr        )
OPER_TYPE_REC(	rm_tr        )
OPER_TYPE_REC(	rm_sreg      )
OPER_TYPE_REC(	rm_max       )
OPER_TYPE_REC(	dacc         )
OPER_TYPE_REC(	eacc         )
OPER_TYPE_REC(	sp           )
OPER_TYPE_REC(	mspu         )
OPER_TYPE_REC(	mspd         )
OPER_TYPE_REC(	m8           )
OPER_TYPE_REC(	bxp          )
OPER_TYPE_REC(	ecx          )
OPER_TYPE_REC(	ax           )
OPER_TYPE_REC(	acc          )
OPER_TYPE_REC(	reg_dx       )
OPER_TYPE_REC(	reg_cl       )
OPER_TYPE_REC(	const_1      )
OPER_TYPE_REC(	const_3      )
OPER_TYPE_REC(	sreg         )
OPER_TYPE_REC(	reg          )
OPER_TYPE_REC(	REG          )
OPER_TYPE_REC(	SREG         )

OPER_TYPE_REC(	fs_gs        )
OPER_TYPE_REC(	imm          )
OPER_TYPE_REC(	imm_8        )
OPER_TYPE_REC(	imm_16       )
OPER_TYPE_REC(	imm_off      )
OPER_TYPE_REC(	imm_seg      )
OPER_TYPE_REC(	imm_far      )
OPER_TYPE_REC(	rel          )
OPER_TYPE_REC(	rel_8        )
OPER_TYPE_REC(	rel_16       )
OPER_TYPE_REC(	next_ip      )
OPER_TYPE_REC(	mem_off      )
OPER_TYPE_REC(	none         ) 
OPER_TYPE_REC(	imp_al       )
OPER_TYPE_REC(	imp_ah       )
OPER_TYPE_REC(	imp_ax       )
OPER_TYPE_REC(	imp_acc      )
OPER_TYPE_REC(	imp_hacc     )
OPER_TYPE_REC(	imp_dacc     )
OPER_TYPE_REC(	dontcare     )
OPER_TYPE_REC(	op1          )
OPER_TYPE_REC(	ds_si        )
OPER_TYPE_REC(	es_di        )
OPER_TYPE_REC(	r16          )
OPER_TYPE_REC(	cflag        )
OPER_TYPE_REC(	const_cf     )
OPER_TYPE_REC(	const_if     )
OPER_TYPE_REC(	const_df     )

#endif